BankSystem/CredoReport/Models/ErrorViewModel.cs
namespace CredoReport.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BankSystem/CredoReport/Models/TransactionStastistic/ChartJsViewModel.cs
namespace CredoReport.Models.TransactionStastistic;

public class ChartJsViewModel
{
    public ChartJs Chart { get; set; }
    public string ChartJson { get; set; }
}

BankSystem/CredoReport/Models/TransactionStastistic/MoneyQuantity.cs
namespace CredoReport.Models.TransactionStastistic;

public class MoneyQuantity
{
    public decimal Quantity { get; set; }
}

BankSystem/CredoReport/Models/TransactionStastistic/TransactionFee.cs
namespace CredoReport.Models.TransactionStastistic;

public class TransactionFee
{
    public decimal GelTotal { get; set; }
    public decimal UsdTotal { get; set; }
    public decimal EuroTotal { get; set; }
}

BankSystem/CredoReport/Models/TransactionStastistic/TransactionQuantity.cs
namespace CredoReport.Models.TransactionStastistic;

public class TransactionQuantity
{
    public int Quantity { get; set; }
}

BankSystem/CredoReport/Models/UserStatistic/UserQuantity.cs
namespace CredoReport.Models.UserStatistic;

public class UserQuantity
{
    public int Quantity { get; set; }
}

BankSystem/CredoReport/Controllers/HomeController.cs
namespace CredoReport.Controllers;

using CredoReport.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BankSystem/CredoReport/Controllers/TransactionStatisticController.cs
namespace CredoReport.Controllers;

using CredoReport.Models.TransactionStastistic;
using CredoReport.Service.Abstractions;
using Mapster;
using Microsoft.AspNetCore.Mvc;

[Route("TransactionStatistic")]
public class TransactionStatisticController : Controller
{
    private readonly ITransactionStatisticService _service;

    public TransactionStatisticController(ITransactionStatisticService service)
    {
        _service = service;
    }

    [Route("Index")]
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [Route("QuantityTransaction")]
    [HttpGet("choseType")]
    public async Task<IActionResult> QuantityTransaction(int choseType)
    {
        var result = await _service.GetTransactionsQuantityService(choseType);
        return View(new TransactionQuantity { Quantity = result });
    }
    [Route("TransactionFeeQuantity")]
    [HttpGet("Id")]
    public async Task<IActionResult> TransactionFeeQuantity(int Id)
    {
        var fee = await _service.GetTotalIncomeService(Id);
        return View(fee.Adapt<TransactionFee>());
    }

    [Route("AverageTransactionFee")]
    [HttpGet]
    public async Task<IActionResult> AverageTransactionFee()
    {
        var averageFee = await _service.GetAvgIncomeService();
        return View(averageFee.Adapt<TransactionFee>());
    }

    [Route("AtmMoneyQuantity")]
    [HttpGet]
    public async Task<IActionResult> AtmMoneyQuantity()
    {
        var result = await _service.GetWithdrawTotalService();
        return View(new MoneyQuantity { Quantity = result });
    }

    [Route("ChartIndex")]
    [HttpGet]
    public async Task<IActionResult> ChartIndex()
    {
        var chart = await _service.GetChartDataService();

        return View(chart.Adapt<ChartJsViewModel>());
    }
}

BankSystem/CredoReport/Controllers/UserStatisticController.cs
namespace CredoReport.Controllers;

using CredoReport.Models.UserStatistic;
using CredoReport.Service.Abstractions;
using Microsoft.AspNetCore.Mvc;

public class UserStatisticController : Controller
{
    private readonly IUserStatisticService userStatistic;

    public UserStatisticController(IUserStatisticService userStatistic)
    {
        this.userStatistic = userStatistic;
    }

    [Route("Index")]
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("{Id}")]
    public async Task<IActionResult> GetUserQuantity(double Id)
    {
        var result = await userStatistic.GetUsersQuantityService(Id);
        return View(new UserQuantity { Quantity = result });
    }
}

BankSystem/CredoReport/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">რეპორტები</h1>
    @Html.ActionLink("მომხმარებლების სტატისტიკა","Index","UserStatistic");
    @Html.ActionLink("ტრანზაქციების სტატისტიკა","Index","TransactionStatistic");
    <vc:chartjs></vc:chartjs>
</div>

BankSystem/CredoReport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CredoReport</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />    
    <link rel="stylesheet" href="~/CredoReport.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CredoReport</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CredoReport - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/Chart.js/chart.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BankSystem/CredoReport/Views/UserStatistic/GetUserQuantity.cshtml
@model CredoReport.Models.UserStatistic.UserQuantity

@{
    ViewData["Title"] = "GetUserQuantity";
}

<h1>მომხმარებლების რაოდენობა</h1>


<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            რაოდენობა
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="GetUserQuantity">
        
        <a asp-action="Index">უკან</a>
    </form>
</div>

BankSystem/CredoReport/Views/UserStatistic/GetUserQuantityFromOneMonth.cshtml
@model CredoReport.Models.UserStatistic.Quantity

@{
    ViewData["Title"] = "GetUserQuantityFromOneMonth";
}

<h1>GetUserQuantityFromOneMonth</h1>

<div>
    <h4>Quantity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserQuantity)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

BankSystem/CredoReport/Views/UserStatistic/GetUserQuantityFromPerMonth.cshtml
@model CredoReport.Models.UserStatistic.UserQuantity

@{
    ViewData["Title"] = "GetUserQuantityFromOneMonth";
}

<h1>GetUserQuantityFromOneMonth</h1>

<div>
    <h4>Quantity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

BankSystem/CredoReport/Views/UserStatistic/Index.cshtml
<div class="text-left">
    <h1 class="display-4">მომხმარებლების სტატისტიკა</h1>
</div>

<ul>
    <li class="nav-item">
        @Html.ActionLink("მიმდინარე წელს დარეგისტრირებული მომხმარებლების რაოდენობა","GetUserQuantity",new {Id=DateTime.Now.Subtract(new DateTime(DateTime.Now.Year, 1, 1)).TotalDays})
    </li>

    <li class="nav-item">
        @Html.ActionLink("ბოლო ერთი წლის განმავლობაში დარეგისტრირებული მომხმარებლების რაოდენობა","GetUserQuantity",new {Id=365})

    </li>

    <li class="nav-item">
        @Html.ActionLink("ბოლო 30 დღეში დარეგისტრირებული მომხმარებლების რაოდენობა","GetUserQuantity",new {Id=30})
    </li>

   
</ul>