BankSystem/MyCredoBanking/Controllers/InnerTransactionController.cs
namespace MyCredoBanking.Controllers;

using BankSystem.Domain.Models;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyCredoBanking.Infrastracture.ServiceCollectionExtensions;
using MyCredoBanking.Models.Response;
using MyCredoBanking.Models.Transaction;
using MyCredoBanking.Service.Abstractions;
using MyCredoBanking.Service.Model;


[Authorize(Roles = "User")]
public class InnerTransactionController : Controller
{
    private readonly UserManager<AppUser> _userManger;
    private readonly IUserService _userService;
    private readonly ITransactionHelperService _transactionHelper;

    public InnerTransactionController(UserManager<AppUser> userManager, IUserService userService
        , ITransactionHelperService transactionHelper)
    {
        _userManger = userManager;
        _userService = userService;
        _transactionHelper = transactionHelper;
    }


    [Route("GetFirstAccount")]
    [HttpGet]
    public async Task<IActionResult> GetFirstAccount()
    {

        var accounts = await _transactionHelper.GetAccounts(_userManger, User.Identity.Name);
        if (accounts is not null)
        {
            return View(accounts.Adapt<List<UserAccountResponse>>());
        }
        return RedirectToAction("EmptyAccount");
    }

    [HttpGet]
    public IActionResult HowMuchMoney(int Id)
    {
        TempData["FirstAccountId"] = Id;

        return View();
    }

    [Route("GetSecondAccount")]
    [HttpPost]
    public async Task<IActionResult> GetSecondAccount(HowMuchMoney howMuch)
    {
        TempData.Put("Amount", howMuch.Amount);

        var firstAccountId = (int)TempData["FirstAccountId"];

        var allAccounts = await _transactionHelper.GetOtherAccounts(_userManger, User.Identity.Name, firstAccountId);

        TempData["FirstAccountId"] = firstAccountId;

        if (allAccounts is not null)
        {
            return View(allAccounts.Adapt<List<UserAccountResponse>>());
        }

        return RedirectToAction("EmptyAccount");
    }

    public async Task<IActionResult> SendToMe(int Id)
    {

        var transaction = new Transaction()
        {
            SenderAccountId = (int)TempData["FirstAccountId"],
            RecieverAccountId = Id,
            Amount = TempData.Get<decimal>("Amount")
        };

        if (await _userService.Transaction(transaction.Adapt<TransactionServiceModel>()))
        {
            return RedirectToAction("Index", "User");
        }

        return RedirectToAction("NotEnoughMoney");
    }

    public IActionResult EmptyAccount()
    {
        return View();
    }

    public IActionResult NotEnoughMoney()
    {
        return View();
    }

}

BankSystem/MyCredoBanking/Controllers/OutherTransactionController.cs
namespace MyCredoBanking.Controllers;

using BankSystem.Domain.Models;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyCredoBanking.Infrastracture.ServiceCollectionExtensions;
using MyCredoBanking.Models.Request;
using MyCredoBanking.Models.Transaction;
using MyCredoBanking.Service.Abstractions;
using MyCredoBanking.Service.Model;


[Authorize(Roles = "User")]
public class OutherTransactionController : Controller
{
    private readonly UserManager<AppUser> _userManger;
    private readonly IUserService _userService;
    private readonly ITransactionHelperService _transactionHelper;

    public OutherTransactionController(UserManager<AppUser> userManager, IUserService userService
        , ITransactionHelperService transactionHelper)
    {
        _userManger = userManager;
        _userService = userService;
        _transactionHelper = transactionHelper;
    }


    [HttpGet]
    public IActionResult GetIdNumber()
    {
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> GetReciverAccounts(IdNumberCheck idNumberCheck)
    {
        var accounts = await _transactionHelper.GetAccoutsWithIdNumber(_userManger, User.Identity.Name, idNumberCheck.IdNumber);

        if (accounts is not null)
        {
            return View(accounts.Adapt<List<UserAccountRequest>>());
        }

        return RedirectToAction("EmptyAccount", "InnerTransaction");
    }

    [HttpGet]
    public IActionResult HowMuchMoney(int Id)
    {
        TempData["AccoundId"] = Id;

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> GetSenderAccounts(HowMuchMoney howMuch)
    {

        TempData.Put("Amount", howMuch.Amount);

        var accounts = await _transactionHelper.GetAccounts(_userManger, User.Identity.Name);

        if (accounts is not null)
        {
            return View(accounts.Adapt<List<UserAccountRequest>>());
        }

        return RedirectToAction("EmptyAccount", "InnerTransaction");
    }

    [Route("SendToOther")]
    [HttpGet("{Id}")]
    public async Task<IActionResult> SendToOther(int Id)
    {

        var transaction = new Transaction()
        {
            RecieverAccountId = (int)TempData["AccoundId"],
            SenderAccountId = Id,
            Amount = TempData.Get<decimal>("Amount")
        };
        if (await _userService.Transaction(transaction.Adapt<TransactionServiceModel>()))
        {
            return RedirectToAction("Index", "User");
        }

        return RedirectToAction("NotEnoughMoney", "InnerTransaction");
    }
}

BankSystem/MyCredoBanking/Controllers/UserController.cs
namespace MyCredoBanking.Controllers;

using BankSystem.Domain.Models;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyCredoBanking.Models.Request;
using MyCredoBanking.Models.Response;
using MyCredoBanking.Service.Abstractions;


[Authorize(Roles = "User")]
public class UserController : Controller
{
    private readonly IUserService _userService;
    private readonly UserManager<AppUser> _userManager;

    public UserController(UserManager<AppUser> userManager, IUserService userService)
    {
        _userService = userService;
        _userManager = userManager;
    }

    [Route("Index")]
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetMyCards()
    {
        var user = await _userManager.FindByNameAsync(User.Identity?.Name);

        var cards = await _userService.GetAllCard(user.Id);
        return View(cards.Adapt<List<CreditCardResponse>>());
    }

    [HttpGet]
    public async Task<IActionResult> GetMyAccounts()
    {
        var user = await _userManager.FindByNameAsync(User.Identity?.Name);

        var accounds = await _userService.GetAllAccount(user.Id);
        return View(accounds.Adapt<List<UserAccountRequest>>());
    }
}

BankSystem/MyCredoBanking/Views/User/GetMyAccounts.cshtml
@model IEnumerable<UserAccountRequest>

@{
    ViewData["Title"] = "UserAccount Page";
}

<table class="table">
    <thead>
        <tr>
            <th>
                ანგარიშის ნომერი
            </th>
            <th>
                არსებული თანხა
            </th>
            <th>
                ვალუტა
            </th>         


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Iban)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Currency)
                </td>
                              
                    
            </tr>
        }
    </tbody>
</table>

BankSystem/MyCredoBanking/Views/User/GetMyCards.cshtml
@model IEnumerable<CreditCardResponse>

@{
    ViewData["Title"] = "CreditCard Page";
}

<table class="table">
    <thead>
        <tr>
            <th>
               ბარათის ნომერი
            </th>
            <th>
                ბარათის ვადა
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cvv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pin)
            </th>
           

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.CardNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CardExpireDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cvv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pin)
                </td>              

               
                
            </tr>
        }        
    </tbody>
   
</table>

BankSystem/MyCredoBanking/Views/User/Index.cshtml
@{
    ViewData["Title"] = "User Page";
}

<div class="text-left">
    <h1 class="display-4">მოგესალმებით</h1>  
</div>

<ul>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetMyCards">ჩემი ბარათები</a>
    </li>

    <li class="nav-item">
         <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetMyAccounts">ჩემი ანგარიშები</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="OutherTransaction" asp-action="GetIdNumber">სხვის ანგარიშზე ჩარიცხვა</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="InnerTransaction" asp-action="GetFirstAccount">ჩემს ანგარიშზე ჩარიცხვა</a>
    </li>
   
</ul>